# TensorFlow 2

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/quickstart/beginner"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

# TensorFlow Tutorial

Until now, you've always used numpy to build neural networks. Now we will step you through a deep learning framework that will allow you to build neural networks more easily. Machine learning frameworks like TensorFlow, PaddlePaddle, Torch, Caffe, Keras, and many others can speed up your machine learning development significantly. All of these frameworks also have a lot of documentation, which you should feel free to read. In this exercise, you will learn to do the following in TensorFlow: 

- Initialize variables
- Train algorithms 
- Build a neural network that classifies images.
- Evaluate the accuracy of the model

Programing frameworks can not only shorten your coding time, but sometimes also perform optimizations that speed up your code. 

You can download and install TensorFlow 2. See the [install guide](https://www.tensorflow.org/install) for details.

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Add, square

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


Now that you have imported the library, we will walk you through its different applications. You will start with an example, where we compute for you the loss of one training example. 
$$loss = \mathcal{L}(\hat{y}, y) = (\hat y^{(i)} - y^{(i)})^2 \tag{1}$$

In [ ]:
y_hat =             # Define y_hat constant. Set to 36.
y =                 # Define y. Set to 39

loss =               # Create a variable for the loss

print(loss)

tf.Tensor(9, shape=(), dtype=int32)


### 1.1 - Linear function

Lets start this programming exercise by computing the following equation: $Y = WX + b$, where $W$ and $X$ are random matrices and b is a random vector. 

**Exercise**: Compute $WX + b$ where $W, X$, and $b$ are drawn from a random normal distribution. W is of shape (4, 3), X is (3,1) and b is (4,1). As an example, here is how you would define a constant X that has shape (3,1):
```python
X = tf.constant(np.random.randn(3,1), name = "X")

```
You might find the following functions helpful: 
- tf.matmul(..., ...) to do a matrix multiplication
- tf.add(..., ...) to do an addition
- np.random.randn(...) to initialize randomly

In [ ]:
# IMPLEMENT FUNCTION: linear_function

def linear_function():
    """
    Implements a linear function: 
            Initializes X to be a random tensor of shape (3,1)
            Initializes W to be a random tensor of shape (4,3)
            Initializes b to be a random tensor of shape (4,1)
    Returns: 
    result -- runs the session for Y = WX + b 
    """
    
    np.random.seed(1)
    
    """
    Note, to ensure that the "random" numbers generated match the expected results,
    please create the variables in the order given in the starting code below.
    (Do not re-arrange the order).
    """
    ### START CODE HERE ### (4 lines of code)
    X = 
    W = 
    b = 
    Y = 
    ### END CODE HERE ### 

    return Y

In [ ]:
print( "result = \n" + str(linear_function()))

result = 
tf.Tensor(
[[-2.15657382]
 [ 2.95891446]
 [-1.08926781]
 [-0.84538042]], shape=(4, 1), dtype=float64)


### 2 - Training MNIST

Load and prepare the [MNIST dataset](http://yann.lecun.com/exdb/mnist/). Convert the samples from integers to floating-point numbers:

In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
#  Normalise inputs
x_train, x_test = x_train / 255.0, x_test / 255.0

Build the `tf.keras.Sequential` model by stacking layers. Choose an optimizer and loss function for training:

In [ ]:
model = tf.keras.models.Sequential([

])

For each example the model returns a vector of "[logits](https://developers.google.com/machine-learning/glossary#logits)" or "[log-odds](https://developers.google.com/machine-learning/glossary#log-odds)" scores, one for each class.

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6253811 ,  0.75982666,  0.5827363 ,  0.07368843,  0.467292  ,
        -0.4970554 ,  0.03149059,  0.0383534 , -0.7802455 ,  0.6406788 ]],
      dtype=float32)

The `tf.nn.softmax` function converts these logits to "probabilities" for each class: 

<img src="https://docs.google.com/uc?export=download&id=1G-n1Cor6jUC6x0CfIpj0oc7YEvL-Pjin" style="width:800px;height:350px;"><caption><center> <u><font color='purple'> **Figure 1**</u><font color='purple'>: Logits <br> <font color='black'> </center>

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.04395984, 0.17564842, 0.1471414 , 0.08844193, 0.1310986 ,
        0.04997897, 0.08478751, 0.0853714 , 0.03765298, 0.15591899]],
      dtype=float32)

Note: It is possible to bake this `tf.nn.softmax` in as the activation function for the last layer of the network. While this can make the model output more directly interpretable, this approach is discouraged as it's impossible to
provide an exact and numerically stable loss calculation for all models when using a softmax output. 

The `losses.SparseCategoricalCrossentropy` loss takes a vector of logits and a `True` index and returns a scalar loss for each example.

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This loss is equal to the negative log probability of the true class:
It is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to `-tf.math.log(1/10) ~= 2.3`.

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.9961529

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

The `Model.fit` method adjusts the model parameters to minimize the loss: 

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4768 - accuracy: 0.8594
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1493 - accuracy: 0.9551
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1062 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0820 - accuracy: 0.9742
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0743 - accuracy: 0.9770


The `Model.evaluate` method checks the models performance, usually on a "[Validation-set](https://developers.google.com/machine-learning/glossary#validation-set)" or "[Test-set](https://developers.google.com/machine-learning/glossary#test-set)".

In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0738 - accuracy: 0.9779


[0.07380051910877228, 0.9779000282287598]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the [TensorFlow tutorials](https://www.tensorflow.org/tutorials/).

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [ ]:
probability_model = tf.keras.Sequential([
                                         
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.37919875e-10, 1.55393320e-09, 2.30214755e-05, 6.04758425e-05,
        6.84916707e-12, 2.30274239e-07, 3.29913099e-14, 9.99915838e-01,
        3.43976971e-08, 4.75841063e-07],
       [1.55844067e-08, 1.36319532e-05, 9.99971867e-01, 1.09733019e-05,
        1.15491015e-15, 4.22846682e-08, 4.26524167e-08, 1.32065691e-13,
        3.40343490e-06, 4.32145071e-15],
       [1.01469716e-07, 9.99426603e-01, 4.72661486e-05, 4.21977393e-06,
        2.10935596e-05, 1.33281901e-05, 1.64167486e-05, 3.82677477e-04,
        8.82452732e-05, 1.54334074e-07],
       [9.98792231e-01, 1.80677709e-10, 1.15866784e-03, 2.83974728e-08,
        7.08630012e-07, 8.80416053e-07, 3.49300753e-05, 8.92725984e-06,
        7.04389880e-09, 3.53752876e-06],
       [7.46329860e-08, 5.02939747e-12, 5.57205567e-06, 8.70356853e-09,
        9.98741329e-01, 1.37613441e-07, 4.07694506e-06, 8.06453409e-06,
        1.37397649e-06, 1.23938243e-03]], dtype=float32)>