# Sistema de Ecuaciones

## 7.1-  ¿Qué es un sistema de ecuaciones?

Un sistema de $m$ ecuaciones con $n$ incógnitas se puede escribir de la siguiente forma:<br><br>
  

<center>$a_{11}\cdot x_1+a_{12}\cdot x_2+...+a_{1n}\cdot x_n=b_1$<br></center>
<center>$a_{21}\cdot x_1+a_{22}\cdot x_2+...+a_{1n}\cdot x_n=b_2$<br></center>
<center>...</center>
<center>$a_{m1}\cdot x_1+a_{m2}\cdot x_2+...+a_{mn}\cdot x_n=b_m$<br></center>  

Como hemos visto en el módulo anterior podemos escribirlo también de la siguiente forma:<br><br>

<center>
$\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n}\\
   a_{21} & a_{22} & ... & a_{2n}\\
   ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn}\\
  \end{array} } \right)\left( {\begin{array}{cc}
   x_{1}\\
   x_{2}\\
   ... \\
   x_{m}\\
  \end{array} } \right) = \left( {\begin{array}{cc}
   b_{1}\\
   b_{2}\\
   ... \\
   b_{m}\\
  \end{array} } \right)$ 
</center><br><br>

Donde se llama **matriz de coeficientes** a:<br>

<center>$A=\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n}\\
   a_{21} & a_{22} & ... & a_{2n}\\
   ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn}\\
  \end{array} } \right)$ 
</center><br><br>
  
Y **matriz ampliada** a:<br><br>

<center>$A^{*}=\left( {\begin{array}{cc}
   a_{11} & a_{12} & ... & a_{1n} & b_{1}\\
   a_{21} & a_{22} & ... & a_{2n} & b_{2}\\
   ... & ... & ... & ... & ...\\
   a_{m1} & a_{m2} & ... & a_{mn} & b_{m}\\
  \end{array} } \right)$ 
</center><br><br>

## 7.2-  Reescribiendo el sistema de ecuaciones

Aunque el título de este apartado suene muy pomposo 🙂, vamos simplemente a aplicar lo que ya sabemos para reescribirlo usando una forma más compacta. Para ello, teniendo en cuenta la **matriz de coeficientes**:<br><br>

<center>$Ax = B$</center>

Donde $A$ es una matriz de $mxn$, $x$ y $B$ son dos vectores columna de longitud $n$. Para poder resolver esta ecuación $Ax = B$ debemos simplemente despejar $x$, para ello:<br>

<center>$Ax = B$</center><br>
<center>$A^{-1}Ax = A^{-1}B$</center><br>
<center>$Ix = A^{-1}B$</center><br>
<center>$x = A^{-1}B$</center><br>


## 7.3-  Determinar si el sistema se puede resolver

Un sistema de ecuaciones lineales pueden tener:
- Una única solución - **sistema compatible determinado**
- Infinitas soluciones - **sistema compatible indeterminado**
- Sin solución - **sistema incompatible**

Vamos allá!

### 7.3.1 -   Sistema compatible determinado

Un sistema de ecuaciones lineales será un **sistema compatible determinado**, es decir tendrá una única solución, cuando el determinante de la matriz $A$ sea igual a 0.

<div class="alert alert-block alert-danger">
    <b><center>$det(A) \neq 0$ - Sistema Compatible Determinado</center></b>
</div>

<div class="alert alert-success">
    <b>Resuelva el siguiente sistema de ecuaciones</b><br><br>
    
<center>
\begin{cases} -x_1 + 2x_3 = 1 \\ x_1 - x_2=-2 \\ x_2 + x_3=-1\end{cases}
</center>
</div> 

Antes que nada vamos descomponerlo y escribirlo como una ecuación matricial de la forma $AX=B$

In [1]:
import numpy as np

A = np.array([[-1, 0, 2],
              [1, -1, 0],
              [0, 1, 1]])

B = np.array([[1],
              [-2],
              [-1]])

print(A)
print(B)

[[-1  0  2]
 [ 1 -1  0]
 [ 0  1  1]]
[[ 1]
 [-2]
 [-1]]


Sabiendo que: $X = A^{-1}B$. El siguiente paso es calcular la matriz inversa de $A$.

In [3]:
# Comprobar si podemos calcular la inversa
np.linalg.det(A)

3.0000000000000004

In [2]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.33333333  0.66666667  0.66666667]
 [-0.33333333 -0.33333333  0.66666667]
 [ 0.33333333  0.33333333  0.33333333]]


Multiplicando:

In [5]:
X = np.dot(A_inv, B)
print("La solucion es: \n", X)

La solucion es: 
 [[-2.33333333]
 [-0.33333333]
 [-0.66666667]]


In [7]:
# Comprobar si el resultado es correcto

B_hat = np.dot(A, X)
print(B_hat)

[[ 1.]
 [-2.]
 [-1.]]


También podemos resolverlo usando:

In [8]:
X = np.linalg.solve(A, B)
print(X)

[[-2.33333333]
 [-0.33333333]
 [-0.66666667]]


Hemos podido calcular la inversa de $A$ porque es cuadrada y el determinante de $A$ es distinto de $0$, sino no podríamos haberlo calcularlo. Podemos comprobar como el determinante de $A$ es distinto de $0$:

In [9]:
det_A = np.linalg.det(A)
print(det_A)

3.0000000000000004


### 7.3.2-   Sistema compatible indeterminado + Sin solución

Considerando el siguiente sistema de ecuaciones:

<center>
\begin{cases} x + 2y -z = 1 \\ -x + y + 2z = 3 \\ x + 5y = 5\end{cases}
</center>

Podemos expresarlo como:

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1\\
   -1 & 1 & 2\\
   1 & 5 & 0\\
  \end{array} } \right)\left( {\begin{array}{cc}
   x\\
   y\\
   z\\
  \end{array} } \right) = \left( {\begin{array}{cc}
   1\\
   3\\
   5\\
  \end{array} } \right)$ </center>
 
Vamos a intentar resolverlo

In [10]:
A = np.array([[1, 2, -1],
              [-1, 1, 2],
              [1, 5, 0]])

B = np.array([[1],
              [3],
              [5]])

Antes que nada vamos a calcular el determinante de $A$ para saber si es $0$ y en ese caso el sistema tiene una única solución, o por lo contratio $det(A)=0$ y por ello es indeterminado o no tiene solución.

Como esperaréis, va a salir $det(A)=0$, de ahí el título de esta sección 🙂

<img src="./Images/einstein.gif" width=20%>

In [11]:
det_A = np.linalg.det(A)
print(det_A)

0.0


**Perfecto!**, el determinante de $A$ es $0$, por lo que o tiene **infinitas soluciones** o no tiene **solución** - ¿Qué podemos hacer para averiguarlo?.

Pues vamos a aplicar el maravilloso **método de eliminación de Gauss** que ya usamos en el módulo de matrices para ver si podemos encontrar un sistema equivalente. En este caso vamos a usar la **matriz ampliada**, por lo que a la matriz $A$ vamos añadirle a la derecha la matriz $B$:

In [13]:
print(A)
print(B)

[[ 1  2 -1]
 [-1  1  2]
 [ 1  5  0]]
[[1]
 [3]
 [5]]


In [14]:
AB = np.concatenate((A, B), axis=1)
AB

array([[ 1,  2, -1,  1],
       [-1,  1,  2,  3],
       [ 1,  5,  0,  5]])

Recordemos que el objetivo del **método de Gauss** es transformar un sistema en otro equivalente que tiene el mismo conjunto solución.<br><br>

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   -1 & 1 & 2 & 3\\
   1 & 5 & 0 & 5\\
  \end{array} } \right)\xrightarrow{f_3 \rightarrow f_3 - f_1}\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   -1 & 1 & 2 & 3\\
   0 & 3 & 1 & 4\\
  \end{array} } \right)$ </center>

In [15]:
AB = np.array([AB[0], AB[1], AB[2] - AB[0]])
AB

array([[ 1,  2, -1,  1],
       [-1,  1,  2,  3],
       [ 0,  3,  1,  4]])

El siguiente pase que podemos hacer es:

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   -1 & 1 & 2 & 3\\
   0 & 3 & 1 & 4\\
  \end{array} } \right)\xrightarrow{f_2 \rightarrow f_2 + f_1}\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   0 & 3 & 1 & 4\\
   0 & 3 & 1 & 4\\
  \end{array} } \right)$ </center>

In [16]:
AB = np.array([AB[0], AB[1] + AB[0], AB[2]])
AB

array([[ 1,  2, -1,  1],
       [ 0,  3,  1,  4],
       [ 0,  3,  1,  4]])

Por último:

El siguiente pase que podemos hacer es:

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   0 & 3 & 1 & 4\\
   0 & 3 & 1 & 4\\
  \end{array} } \right)\xrightarrow{f_3 \rightarrow f_3 - f_2}\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   0 & 3 & 1 & 4\\
   0 & 0 & 0 & 0\\
  \end{array} } \right)$ </center>

In [17]:
AB = np.array([AB[0], AB[1], AB[2] - AB[1]])
AB

array([[ 1,  2, -1,  1],
       [ 0,  3,  1,  4],
       [ 0,  0,  0,  0]])

Con los pasos que hemos realizado hemos obtenido un sistema equivalente de ecuaciones al inicial, podemos intentar resolverlo, usando `numpy` directamente:

In [22]:
A = AB[:, :3] # Matriz A
print(A)

[[ 1  2 -1]
 [ 0  3  1]
 [ 0  0  0]]


In [23]:
B = AB[:, -1] # Matriz B
print(B)

[1 4 0]


In [24]:
X = np.linalg.solve(A, B)
X

LinAlgError: Singular matrix

Como vemos `numpy` no es capaz de resolver este tipo de sistema de ecuaciones lineales, vamos a intentar resolverlo usando `sympy`.

Simplemente debemos escribir la ecuación $AB$ y usar `solve()`<br><br>

<center>
\begin{cases} x + 2y -z = 1 \\ 3y + z = 4\end{cases}
</center>

Igualando a $0$:<br><br>

<center>
\begin{cases} x + 2y -z -1 = 0 \\ 3y + z -4 = 0\end{cases}
</center>

In [25]:
print(A)
print(B)

[[ 1  2 -1]
 [ 0  3  1]
 [ 0  0  0]]
[1 4 0]


In [26]:
from sympy.solvers import *
from sympy import *

# Definir las variables que queremos resolver
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

fun1 = x + 2*y - 1*z - 1
fun2 = 3*y + z - 4

solucion = solve([fun1, fun2], [x, y, z])
print(f"Solucion: {solucion}")

Solucion: {x: 5*z/3 - 5/3, y: 4/3 - z/3}


**mmmm que raro...** Nuestra solución depende de $z$, si lo pensamos bien eso se debe a que tiene $\infty$ soluciones, ya que depende directamente de $z$. Habrá una solución para $z=1$, $z=20$, ... $z=1324573$. Más en profundidad, dicha solución es un conjunto de rectas. [Aquí lo explican muy bien.](https://www.montereyinstitute.org/courses/DevelopmentalMath/TEXTGROUP-9-14_RESOURCE/U14_L1_T1_text_final_es.html)

<img src="./Images/planos.png" width=60%>

Podemos evaluar la solución usando `evalf`, por ejemplo para <b>$z=6$</b>:

In [29]:
print(solucion)
print(solucion[x])
print(solucion[y])

{x: 5*z/3 - 5/3, y: 4/3 - z/3}
5*z/3 - 5/3
4/3 - z/3


In [31]:
solucion_x = solucion[x].evalf(subs={z:6})
solucion_y = solucion[y].evalf(subs={z:6})

In [32]:
z = 6

print("Solucion z=6")
print(f"x: {solucion_x}")
print(f"y: {solucion_y}")
print(f"z: {z}")

Solucion z=6
x: 8.33333333333333
y: -0.666666666666667
z: 6


### Sin solución

Ya hemos encontrado un sistema de ecuaciones lineales que tiene infinitas soluciones, vamos a intentar resolver uno para ver que sucede cuando **el sistema de ecuaciones no tiene solución.**

<center>
\begin{cases} x + 2y -z = 1 \\ -x + y + 2z = 3 \\ x + 5y = 0\end{cases}
</center>

Podemos expresarlo como:

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1\\
   -1 & 1 & 2\\
   1 & 5 & 0\\
  \end{array} } \right)\left( {\begin{array}{cc}
   x\\
   y\\
   z\\
  \end{array} } \right) = \left( {\begin{array}{cc}
   1\\
   3\\
   0\\
  \end{array} } \right)$ </center>
 
Vamos a usar el mismo proceso que antes para poder encontrar un sistema de ecuaciones similar al inicial:<br><br>

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   -1 & 1 & 2 & 3\\
   1 & 5 & 0 & 0\\
  \end{array} } \right)\xrightarrow{f_3 \rightarrow f_3 - f_1}\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   -1 & 1 & 2 & 3\\
   0 & 3 & 1 & -1\\
  \end{array} } \right)$ </center>

In [2]:
import numpy as np
A = np.array([[1, 2, -1],
              [-1, 1, 2],
              [1, 5, 0]])

B = np.array([[1],
              [3],
              [0]])

AB = np.concatenate((A, B), axis=1)
print(AB)

[[ 1  2 -1  1]
 [-1  1  2  3]
 [ 1  5  0  0]]


In [3]:
AB = np.array([AB[0], AB[1], AB[2] - AB[0]])
AB

array([[ 1,  2, -1,  1],
       [-1,  1,  2,  3],
       [ 0,  3,  1, -1]])

El siguiente paso que podemos realizar es:<br><br>

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   -1 & 1 & 2 & 3\\
   0 & 3 & 1 & -1\\
  \end{array} } \right)\xrightarrow{f_2 \rightarrow f_2 + f_1}\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   0 & 3 & 1 & 4\\
   0 & 3 & 1 & -1\\
  \end{array} } \right)$ </center>

In [4]:
AB_ = np.array([AB[0], AB[1] + AB[0], AB[2]])
AB_

array([[ 1,  2, -1,  1],
       [ 0,  3,  1,  4],
       [ 0,  3,  1, -1]])

Por último:<br><br>

<center>$\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   0 & 3 & 1 & 4\\
   0 & 3 & 1 & -1\\
  \end{array} } \right)\xrightarrow{f_3 \rightarrow f_3 - f_2}\left( {\begin{array}{cc}
   1 & 2 & -1 & 1\\
   0 & 3 & 1 & 4\\
   0 & 0 & 0 & -5\\
  \end{array} } \right)$ </center>

In [5]:
AB = np.array([AB_[0], AB_[1], AB_[2]-AB_[1]])
AB

array([[ 1,  2, -1,  1],
       [ 0,  3,  1,  4],
       [ 0,  0,  0, -5]])

La última fila de la matriz ya nos indica que algo raro sucede, porque $0 = -5$ no tiene sentido. Aún así vamos a resolverlo usando `sympy`:<br><br>

<center>
\begin{cases} x + 2y -z = 1 \\ 3y + z = 4 \\ 0 = -5\end{cases}
</center>

Igualando a $0$:<br><br>

<center>
\begin{cases} x + 2y -z -1 = 0 \\ 3y + z -4 = 0 \\ 0 = -5\end{cases}
</center>


In [6]:
from sympy.solvers import *
from sympy import *

# Definir las variables que queremos resolver
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

fun1 = x + 2*y - z - 1
fun2 = 3*y + z - 4
fun3 = -5

In [7]:
solucion = solve([fun1, fun2, fun3], [x, y, z])

In [8]:
print(solucion)

[]


La solución está vacía, lo que indica que este sistema de ecuaciones lineales no tiene solución y por tanto es un **sistema incompatible**.

### Resumiendo

AX = B

<img src="./Images/secuaciones.png" width=50%>

Esto es válido para cuando $B \neq 0 $, pero si en el sistema de ecuaciones $B = 0$ dicho sistema se denomina **sistema homogéneo** y son siempre **compatibles**, es decir siempre tiene alguna solución. Y la verdad es que tiene sentido porque siempre van a admitir la solución trivial de $X=0$.

<img src="./Images/secuaciones_h.png" width=50%>


### Ejemplo
¿Sabéis típico juego que te aparece en facebook de calcular el valor de distintos objetos?

<img src="./Images/ejemplo_eq.jpg" width=50%>

Bueno pues todos ellos se resuelven siempre de la misma forma, usando un **sistema de ecuaciones lineales**. Así que vamos a intentar resolver uno de ellos!

<div class="alert alert-success">
    <b>EL MERCADO GANADERO</b><br><br>
    
<img src="Images/ganado.jpg" style="width: 300px;"/>

Tres campesinos se encontraron en el mercado ganadero.
- Mira, le dijo Luis a Juan, te daré 6 de mis cerdos por 1 de tus caballos y así tendrás el doble de animales que yo.
- Si ése es tu modo de hacer negocios, le dijo Pepe a Luis, te daré 14 ovejas por 1 caballo, y entonces tendrás el triple de animales que yo.
- Bien, le dijo Juan a Pepe. Te daré 4 vacas por un caballo y entonces tendrás seis veces más animales que yo.

<b>¿Cuántos animales llevaron al mercado Juan, Luis y Pepe?</b>
</div><br>

Llamemos $L$ al número de animales que tiene Luis, $J$ al número de animales que posee Juan y $P$ al número de animales pertenecientes a Pepe. Si analizamos el párrafo y lo convertimos a ecuaciones:<br><br>

<center>$J-1+6=2·(L-6+1)$</center>
<center>$L-1+14=3·(P-14+1)$</center>
<center>$P+4-1=6·(J+1-4)$</center>
  
Reagrupando:<br>

<center>$J-2L = -15$</center>
<center>$L-3P = -52$</center>
<center>$P-6J = -21$</center>
|
Usando `numpy':

In [9]:
import numpy as np

# J, L , P
A = np.array([[1, -2, 0],
              [0, 1, -3],
              [-6, 0, 1]])

B = np.array([[-15],
              [-52],
              [-21]])

print("Determinante: ", np.linalg.det(A))

Determinante:  -35.00000000000001


In [10]:
X = np.linalg.solve(A, B)
print(X)

[[ 7.]
 [11.]
 [21.]]


J - 1 + 6 = 2*L - 12 + 2 <br>
J + 5 = 2*L - 10<br>
J - 2*L = -15<br>